added more verbose output

diff --git a/glasscordctl b/glasscordctl
--- a/glasscordctl
+++ b/glasscordctl
@@ -4,18 +4,22 @@
 VERSION=0.0.1
 DISCORD_PATH="${HOME}/.config/discord"
 GLASSCORD_PATH="${DISCORD_PATH}/glasscord"
+USED_DISCORD_VERSION_FILE="${GLASSCORD_PATH}/used_discord_version"
+GLASSCORD_VERSION_FILE="${GLASSCORD_PATH}/glasscord_version"
 
-HELPMSG="Glasscordctl version ${VERSION}\n\ninstall - installs glasscord\nupdate - updates an installation\nuninstall - uninstalls glasscord"
+HELPMSG="Glasscordctl version ${VERSION}\n\ninstall - installs glasscord\nupdate - updates an installation\nuninstall - uninstalls glasscord\nreinstall - uninstalls and then installs glasscord\nhelp - shows this message\nversion - prints the version of this script\ninfo - print info about install"
 
-# Make sure info files exist
-[ -d "${GLASSCORD_PATH}" ] || mkdir -p "${GLASSCORD_PATH}"
-
-# Gives you the link to the latest release
 latest_release_link () {
-	echo "https://github.com/AryToNeX/Glasscord/releases/download/v0.0.6/glasscord.asar"
-#	echo https://github.com$(curl https://github.com/AryToNeX/Glasscord/releases/latest -L &>/dev/null | grep '\.asar' | sed '1q' | cut -d '"' -f 2)
+	curl "https://api.github.com/repos/AryToNex/Glasscord/releases/latest" -s | awk '/browser_download_url/ { print $2 }' | cut -d '"' -f 2
 }
 
+latest_glasscord_version () {
+	curl "https://api.github.com/repos/AryToNex/Glasscord/releases/latest" -s | awk '/tag_name/ { print $2 }' | cut -d '"' -f 2
+}
+
+used_glasscord_version () {
+	cat "${GLASSCORD_VERSION_FILE}"
+}
 
 # Gives you the latest version of discord
 discord_versions () {
@@ -29,7 +33,7 @@ latest_discord_version () {
 
 # Gives you the used version of discord
 used_discord_version () {
-	cat "${GLASSCORD_PATH}/used_discord_version"
+	cat "${USED_DISCORD_VERSION_FILE}"
 }
 
 # Takes 1 arg an installs to that dir
@@ -42,7 +46,7 @@ install_to () {
 
 # Check if it should move to another directory
 update () {
-	if [ ! -f "${GLASSCORD_PATH}/used_discord_version" ]; then
+	if [ ! -f "${USED_DISCORD_VERSION_FILE}" ]; then
 		echo "Can't update before install"
 		return
 	fi
@@ -58,19 +62,50 @@ update () {
 	else
 		echo "Already installed for latest discord version"
 	fi
+
+	if [[ `used_glasscord_version` != `latest_glasscord_version` ]]; then
+		echo "Downloading latest release of Glasscord."
+		curl `latest_release_link` -sLo "${GLASSCORD_PATH}/glasscord.asar" &&\
+		echo `latest_glasscord_version` > "${GLASSCORD_VERSION_FILE}" || {
+			echo "Update failed, if you can no longer launch the older version, please uninstall and install Glasscord"
+		}
+	else
+		echo "Already installed latest Glasscord version."
+	fi
 }
 
 install () {
-	curl `latest_release_link` -Lo "${GLASSCORD_PATH}/glasscord.asar" &&\
-	install_to `latest_discord_version` &&\
-	latest_discord_version > "${GLASSCORD_PATH}/used_discord_version"
+	if [ ! -d ${DISCORD_PATH} ]; then
+		echo "Your discord directory doesn't seem to exist, if you are sure you have discord installed, please find it's config directory, then edit the variable called 'DISCORD_PATH' at the top of this file to match it"
+		exit
+	fi
+
+	if [ ! -d ${GLASSCORD_PATH} ]; then
+		mkdir -p "${GLASSCORD_PATH}"
+		curl `latest_release_link` -sLo "${GLASSCORD_PATH}/glasscord.asar" &&\
+		install_to `latest_discord_version` &&\
+		latest_discord_version > "${USED_DISCORD_VERSION_FILE}" &&\
+		`latest_glasscord_version` > "${GLASSCORD_VERSION_FILE}" || {
+			echo "Installation failed, removing files."
+			uninstall
+			exit
+		}
+		echo "Sucessfully updated Glasscord"
+	else
+		echo "Already installed"
+	fi
 }
 
 uninstall () {
-	for version in `discord_versions`; do
-		uninstall_from ${version}
-	done
-	[ -d "${GLASSCORD_PATH}" ] && rm "${GLASSCORD_PATH}"
+	if [ -d ${GLASSCORD_PATH} ]; then
+		for version in `discord_versions`; do
+			uninstall_from ${version}
+		done
+		rm "${GLASSCORD_PATH}"
+		echo "Sucessfully uninstalled Glasscord"
+	else
+		echo "Glasscord is not installed"
+	fi
 }
 
 case $1 in
@@ -83,10 +118,21 @@ case $1 in
 	uninstall)
 		uninstall
 		;;
+	reinstall)
+		uninstall
+		install
+		;;
 	help)
-		echo -e ${HELPMSG}
+		echo -e "${HELPMSG}"
 		;;
 	version)
-		echo -e ${VERSION}
+		echo -e "${VERSION}"
+		;;
+	info)
+		if [ -d ${GLASSCORD_PATH} ]; then
+			echo -e "Discord version: `used_discord_version` Glasscord version: `used_glasscord_version`"
+		else
+			echo "Glasscord is not installed"
+		fi
 		;;
 esac
